### ISSUE TITLE
Catch-all Meteor's errors example: [Server] problems

### ISSUE THREAD

**Issue by mahadoang** [VeliovGroup/Meteor-logger-mongo#23]
ostrio:logger@2.0.8
ostrio:loggermongo@2.0.5
METEOR@1.8.0.2

Error Message not log

**code** 
```
const originalMeteorDebug = Meteor._debug;
Meteor._debug = function (message, stack) {
  const error = new Error(message);
  error.stack = stack;
  log.error('Meteor Error!', error);
  return originalMeteorDebug.apply(this, arguments);
};
```
Metero Error :

```
I20190218-11:25:02.855(7)? Exception while invoking method 'channel.get' ReferenceError: LIMIT_PER_PAGE_1 is not defined
I20190218-11:25:02.856(7)?     at MethodInvocation.channel.get (src/imports/api/channel/methods.js:30:48)
I20190218-11:25:02.857(7)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)
I20190218-11:25:02.857(7)?     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
I20190218-11:25:02.858(7)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
I20190218-11:25:02.858(7)?     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
I20190218-11:25:02.858(7)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
I20190218-11:25:02.858(7)?     at Promise (packages/ddp-server/livedata_server.js:715:46)
I20190218-11:25:02.859(7)?     at new Promise (<anonymous>)
I20190218-11:25:02.859(7)?     at Session.method (packages/ddp-server/livedata_server.js:689:23)
I20190218-11:25:02.859(7)?     at packages/ddp-server/livedata_server.js:559:43

```
Mongo

```
{
  "_id": "GBAGQYXrh8B3TXfn7",
  "userId": null,
  "date": new Date(1550463902675),
  "timestamp": 1550463902675.0,
  "level": "ERROR",
  "message": "Meteor Error!",
  "additional": {

  }
}

```
Thank you.

**Comment by dr-dimitru** [comment]
Hello @mahadoang 👋

From error message I see you have an issue with undefined variable `LIMIT_PER_PAGE_1` in a file `src/imports/api/channel/methods.js` on line `30`.

Record from mongo looks good, for the details I may suggest to use plain *Object* instead of `Error` instance:

```js
const originalMeteorDebug = Meteor._debug;
Meteor._debug = function (message, stack) {
  // const error = new Error(message);
  // error.stack = stack;
  log.error('Meteor Error!', message); // Or maybe even {message: JSON.stringify(message)}
  return originalMeteorDebug.apply(this, arguments);
};
```

Is it a case?

**Comment by mahadoang** [comment]
```
{
  "_id": "LKbb5sZ67pP6v79Wo",
  "userId": null,
  "date": new Date(1550464967063),
  "timestamp": 1550464967063.0,
  "level": "ERROR",
  "message": "Meteor Error!",
  "additional": "Exception while invoking method 'channel.get'"
}
```

how to Record message with the file and line number.

```
Exception while invoking method 'channel.get
at MethodInvocation.channel.get (src/imports/api/channel/methods.js:30:48)

```

**Comment by dr-dimitru** [comment]
@mahadoang make sure you have no *Circular Objects*, only plain object can be submitted as second argument.

Try your original code, but log `error` argument before calling `.error()` method:

```js
const originalMeteorDebug = Meteor._debug;
Meteor._debug = function (message, stack) {
  const error = new Error(message);
  error.stack = stack;
  console.log(error);
  log.error('Meteor Error!', error);
  return originalMeteorDebug.apply(this, arguments);
};
```

Very curious to see output of `console.log(error);`

**Comment by mahadoang** [comment]
@dr-dimitru Thanks you, 

```
const originalMeteorDebug = Meteor._debug;
Meteor._debug = function (message, stack) 
{
    const error = new Error(message);
    error.stack = stack;
    console.log('-----------');
    console.log('Meteor Error!',error);
    console.log('-----------');
    log.error('Meteor Error!', error);
    return originalMeteorDebug.apply(this, arguments);
};
```

```
=> Meteor server restarted                    
I20190222-08:54:20.463(7)? -----------
I20190222-08:54:20.464(7)? Meteor Error! ReferenceError: LIMIT_PER_PAGE_1 is not defined
I20190222-08:54:20.465(7)? -----------
I20190222-08:54:20.632(7)? Exception while invoking method 'channel.get' ReferenceError: LIMIT_PER_PAGE_1 is not defined
I20190222-08:54:20.632(7)?     at MethodInvocation.channel.get (src/imports/api/channel/methods.js:30:48)
I20190222-08:54:20.633(7)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)
I20190222-08:54:20.633(7)?     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
I20190222-08:54:20.633(7)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
I20190222-08:54:20.634(7)?     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
I20190222-08:54:20.634(7)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
I20190222-08:54:20.634(7)?     at Promise (packages/ddp-server/livedata_server.js:715:46)
I20190222-08:54:20.635(7)?     at new Promise (<anonymous>)
I20190222-08:54:20.635(7)?     at Session.method (packages/ddp-server/livedata_server.js:689:23)
I20190222-08:54:20.636(7)?     at packages/ddp-server/livedata_server.js:559:43



```


```
const originalMeteorDebug = Meteor._debug;
Meteor._debug = function (message, stack) 
{
    const error = new Error(message);
    error.stack = stack;
    console.log('-----------');
    console.log(error);
    console.log('-----------');
    log.error('Meteor Error!', error);
    return originalMeteorDebug.apply(this, arguments);
};
```


```
=> Meteor server restarted                    
I20190222-08:58:22.002(7)? -----------
I20190222-08:58:22.003(7)? ReferenceError: LIMIT_PER_PAGE_1 is not defined
I20190222-08:58:22.003(7)? -----------
I20190222-08:58:22.193(7)? Exception while invoking method 'channel.get' ReferenceError: LIMIT_PER_PAGE_1 is not defined
I20190222-08:58:22.193(7)?     at MethodInvocation.channel.get (src/imports/api/channel/methods.js:30:48)
I20190222-08:58:22.194(7)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)
I20190222-08:58:22.194(7)?     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
I20190222-08:58:22.194(7)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
I20190222-08:58:22.195(7)?     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
I20190222-08:58:22.195(7)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
I20190222-08:58:22.195(7)?     at Promise (packages/ddp-server/livedata_server.js:715:46)
I20190222-08:58:22.195(7)?     at new Promise (<anonymous>)
I20190222-08:58:22.195(7)?     at Session.method (packages/ddp-server/livedata_server.js:689:23)
I20190222-08:58:22.196(7)?     at packages/ddp-server/livedata_server.js:559:43

```

**Comment by dr-dimitru** [comment]
Well, `error` isn't a plain JS *Object* in your case.

try:

```js
const originalMeteorDebug = Meteor._debug;
Meteor._debug = function (message, stack) {
  const additional = { message };
  const error = new Error(message);
  additional.stack = stack;
  console.log(additional);
  log.error('Meteor Error!', additional);
  return originalMeteorDebug.apply(this, arguments);
};
```

Actually for stack trace we have special [`.trace()` method](https://github.com/VeliovGroup/Meteor-logger/blob/1985c336f9786b09a7031cd0323ea80d1b29f690/logger.js#L247):

```js
const originalMeteorDebug = Meteor._debug;
Meteor._debug = function (message, stack) {
  log.trace('Meteor Error!', message);
  return originalMeteorDebug.apply(this, arguments);
};
```

**Comment by mahadoang** [comment]
```
Meteor._debug = function (message, stack) 
{
    const additional = { message };
    additional.stack = stack;
    console.log(additional);
    log.error('Meteor Error!', additional);
    return originalMeteorDebug.apply(this, arguments);
}

```

```
I20190222-09:17:00.584(7)? { message: 'Exception while invoking method \'channel.get\'',
I20190222-09:17:00.584(7)?   stack: ReferenceError: LIMIT_PER_PAGE_1 is not defined
I20190222-09:17:00.584(7)?     at MethodInvocation.channel.get (src/imports/api/channel/methods.js:30:48)
I20190222-09:17:00.585(7)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)
I20190222-09:17:00.585(7)?     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
I20190222-09:17:00.585(7)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
I20190222-09:17:00.585(7)?     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
I20190222-09:17:00.586(7)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
I20190222-09:17:00.586(7)?     at Promise (packages/ddp-server/livedata_server.js:715:46)
I20190222-09:17:00.586(7)?     at new Promise (<anonymous>)
I20190222-09:17:00.587(7)?     at Session.method (packages/ddp-server/livedata_server.js:689:23)
I20190222-09:17:00.587(7)?     at packages/ddp-server/livedata_server.js:559:43 }
```


MongoDB

```
{
  "_id": "YDGc4jTdEGyK2XhaN",
  "userId": null,
  "date": new Date(1550801683479),
  "timestamp": 1550801683479.0,
  "level": "ERROR",
  "message": "Meteor Error!",
  "additional": {
    "message": "Exception while invoking method 'channel.get'",
    "stack": {

    }
  }
}
```

**Comment by mahadoang** [comment]
@dr-dimitru Thanks you.
i fixed.

`https://forums.meteor.com/t/error-messages-in-server-now-show-as-exception-while-invoking-method-methodname-object-object-since-upgrading-to-1-7/44542/4`


```
import util from 'util';

const originalMeteorDebug = Meteor._debug;
Meteor._debug = function (message, stack) 
{
    const additional = { message };
    additional.stack = util.inspect(stack, false, null).split('\n');
    log.error('Meteor Error!', additional);
    return originalMeteorDebug.apply(this, arguments);
};


```

MongDB

```
{
  "_id": "o4qxvnxaZAbwapGtN",
  "userId": null,
  "date": new Date(1550807652473),
  "timestamp": 1550807652473.0,
  "level": "ERROR",
  "message": "Meteor Error!",
  "additional": {
    "message": "Exception while invoking method 'channel.get'",
    "stack": [
      "ReferenceError: LIMIT_PER_PAGE_1 is not defined",
      "    at MethodInvocation.channel.get (src/imports/api/channel/methods.js:30:48)",
      "    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)",
      "    at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)",
      "    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)",
      "    at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)",
      "    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)",
      "    at Promise (packages/ddp-server/livedata_server.js:715:46)",
      "    at new Promise (<anonymous>)",
      "    at Session.method (packages/ddp-server/livedata_server.js:689:23)",
      "    at packages/ddp-server/livedata_server.js:559:43"
    ]
  }
}
```

**Comment by dr-dimitru** [comment]
Shall we update it in our docs? @mahadoang do you wish to send a PR?
